name: build portfolio.cli

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  build:
    needs:
      - ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build binary
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          outputs: output
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: portfolio.cli
          path: ./output