name: deploy binary

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build binary
    uses: ./.github/workflows/build.yml
  deploy:
    name: Deploy binary
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: portfolio.cli
          path: ./output
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./output